# Generated by Django 6.0.1 on 2026-01-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
    ]
