# Generated by Django 6.0.1 on 2026-01-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='trait',
            field=models.CharField(choices=[('O', 'Openness'), ('C', 'Conscientiousness'), ('E', 'Extraversion'), ('A', 'Agreeableness'), ('N', 'Neuroticism')], max_length=1),
        ),
    ]
